-- ===========================================================================
-- 001 — esquema inicial do sistema de gestão (/restrito) no PostgreSQL
--
-- Tradução fiel do que existia no SQLite (data/gestao.db), já com TODAS as
-- colunas que antes eram acrescentadas por uma lista de ALTER TABLE no boot.
-- Daqui em diante, mudança de esquema é um arquivo novo nesta pasta — nunca
-- mais ALTER dentro de try/catch, que escondia erro de digitação por anos.
--
-- DUAS DECISÕES DE TIPO, tomadas para NÃO mexer na aplicação:
--
--  · Os liga/desliga (ativo, arquivado, consentimento, primeira, encaixe…)
--    continuam INTEGER 0/1, e não BOOLEAN. Virar boolean obrigaria a rever
--    cada `ativo=1` do SQL, cada JSON que a tela manda e cada `if (x.ativo)`
--    do JavaScript. O ganho seria estético; o risco, real.
--
--  · As datas continuam TEXT no formato ISO ('2026-07-28', '2026-07-28T13:05:00Z'),
--    e não DATE/TIMESTAMP. É como o sistema já grava, compara e ordena — e a
--    ordenação alfabética de ISO é a ordenação cronológica. Converter agora
--    mudaria o que a API devolve para a tela (o driver entregaria objeto Date
--    no lugar da string) e quebraria as impressões.
--
-- Quando fizer sentido migrar esses tipos, será um passo próprio, com teste —
-- não de carona numa troca de banco.
-- ===========================================================================

-- Operadores do sistema (login). perfil: admin | profissional | secretaria.
-- profissional_id liga um usuário-profissional ao seu registro na tabela
-- profissionais — é assim que ele enxerga "a SUA agenda".
CREATE TABLE IF NOT EXISTS g_usuarios (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  email           TEXT UNIQUE,
  senha_hash      TEXT NOT NULL,
  perfil          TEXT NOT NULL DEFAULT 'admin',
  ativo           INTEGER DEFAULT 1,
  profissional_id INTEGER,
  criado          TEXT
);

-- Configurações internas do sistema (chave/valor). Guarda também os contadores
-- de numeração (pront_seq_2026, pac_seq_2026) e as travas de seed.
CREATE TABLE IF NOT EXISTS g_config (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- Pacientes. Espelha a ficha de cadastro usada pela recepção.
-- "codigo" (PAC-AAAA-00000) é o identificador PRÓPRIO do paciente, gerado pelo
-- servidor e NUNCA digitado. Não confundir com o número do PRONTUÁRIO
-- (PR-AAAA-00000): o paciente tem um código só, e um prontuário para cada
-- procedimento que faz.
CREATE TABLE IF NOT EXISTS pacientes (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo         TEXT,
  nome           TEXT NOT NULL,
  nome_contato   TEXT,
  foto           TEXT,
  juridica       INTEGER DEFAULT 0,
  estrangeiro    INTEGER DEFAULT 0,
  cpf            TEXT,
  rg             TEXT,
  sexo           TEXT,
  nascimento     TEXT,
  naturalidade   TEXT,
  estado_civil   TEXT,
  convenio_id    INTEGER,
  religiao       TEXT,
  profissao      TEXT,
  escolaridade   TEXT,
  altura         TEXT,
  peso           TEXT,
  cor_pele       TEXT,
  prioridade     TEXT,
  sangue         TEXT,
  cep            TEXT,
  endereco       TEXT,
  numero         TEXT,
  bairro         TEXT,
  cidade         TEXT,
  complemento    TEXT,
  celular        TEXT,
  telefone       TEXT,
  email          TEXT,
  canal          TEXT,
  mae            TEXT,
  pai            TEXT,
  tag            TEXT,
  indicacao      TEXT,
  avisos         INTEGER DEFAULT 1,
  resp_nome      TEXT,
  resp_cpf       TEXT,
  resp_rg        TEXT,
  resp_nascimento TEXT,
  consentimento  INTEGER DEFAULT 0,
  observacao     TEXT,
  criado         TEXT,
  reativado_em   TEXT,
  -- ativo: o paciente ainda frequenta a clínica. Inativo some das telas de
  -- escolha mas NUNCA é excluído. Não confundir com a ALTA, que é de um
  -- prontuário só (alta da ozonioterapia, segue na psicanálise).
  ativo          INTEGER DEFAULT 1,
  inativo_em     TEXT,
  inativo_motivo TEXT
);

-- Convênios aceitos (Particular, Cartão BemEstarClinic, System Saúde…)
CREATE TABLE IF NOT EXISTS convenios (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome       TEXT NOT NULL,
  registro   TEXT,
  contato    TEXT,
  observacao TEXT,
  ativo      INTEGER DEFAULT 1,
  sort       INTEGER DEFAULT 0,
  criado     TEXT
);

-- Procedimentos: cada linha é "o que se agenda". tipo = Consulta | Sessão |
-- Procedimento. ATENÇÃO ao par nome/tipo: "Ozonioterapia" existe duas vezes,
-- uma como Consulta e outra como Sessão. O que identifica o TRATAMENTO é o
-- "nome" — é ele que vira a chave do prontuário, não o id da linha.
-- anamnese_modelo diz qual formulário este procedimento pede
-- (psicanalise | ozonio | integrativas | vazio = nenhum).
CREATE TABLE IF NOT EXISTS procedimentos (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  tipo            TEXT DEFAULT 'Consulta',
  valor           TEXT,
  duracao         INTEGER DEFAULT 40,
  cor             TEXT,
  anamnese_modelo TEXT,
  ativo           INTEGER DEFAULT 1,
  sort            INTEGER DEFAULT 0,
  criado          TEXT
);

-- Salas / consultórios
CREATE TABLE IF NOT EXISTS salas (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   TEXT NOT NULL,
  ativo  INTEGER DEFAULT 1,
  sort   INTEGER DEFAULT 0,
  criado TEXT
);

-- Profissionais. "especialidade" guarda um JSON array dos procedimentos que
-- ele realiza; "cor" identifica a agenda dele.
CREATE TABLE IF NOT EXISTS profissionais (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,
  especialidade TEXT,
  registro      TEXT,
  contato       TEXT,
  cor           TEXT,
  ativo         INTEGER DEFAULT 1,
  criado        TEXT
);

-- Agenda de atendimentos.
-- Só se agenda para paciente CADASTRADO — é o que garante que todo atendimento
-- tenha ficha, código e histórico.
-- prontuario_id: o agendamento NÃO cria prontuário. Ele só se liga a um que JÁ
-- exista para aquele paciente naquele procedimento; no primeiro atendimento
-- fica nulo, e o vínculo acontece quando a anamnese é finalizada.
CREATE TABLE IF NOT EXISTS atendimentos (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id     INTEGER,
  profissional_id INTEGER,
  sala_id         INTEGER,
  convenio_id     INTEGER,
  procedimento_id INTEGER,
  especialidade   TEXT,
  prontuario_id   INTEGER,
  nome_agenda     TEXT,
  celular         TEXT,
  data            TEXT,
  hora            TEXT,
  hora_fim        TEXT,
  valor           TEXT,
  primeira        INTEGER DEFAULT 0,
  encaixe         INTEGER DEFAULT 0,
  lembrete        INTEGER DEFAULT 1,
  nps             INTEGER DEFAULT 1,
  status          TEXT DEFAULT 'Agendado',
  observacoes     TEXT,
  criado          TEXT
);

-- PRONTUÁRIO = a PASTA do paciente numa especialidade.
-- Um prontuário por paciente + especialidade (índice único mais abaixo).
-- numero (PR-AAAA-00000) identifica a pasta.
-- status: Ativo | Alta. A alta é DO PRONTUÁRIO.
CREATE TABLE IF NOT EXISTS prontuario (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero        TEXT,
  paciente_id   INTEGER NOT NULL,
  especialidade TEXT NOT NULL,
  profissional  TEXT,
  status        TEXT DEFAULT 'Ativo',
  aberto_em     TEXT,
  alta_em       TEXT,
  alta_motivo   TEXT,
  observacao    TEXT,
  usuario_id    INTEGER,
  criado        TEXT,
  reativado_em  TEXT
);

-- LANÇAMENTOS do prontuário. Cada avaliação, evolução, plano ou encaminhamento
-- é uma linha datada. arquivado: some das telas mas NUNCA é excluído.
CREATE TABLE IF NOT EXISTS prontuario_registros (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prontuario_id INTEGER NOT NULL,
  tipo          TEXT NOT NULL,
  texto         TEXT,
  data          TEXT,
  profissional  TEXT,
  anexo         TEXT,
  arquivado     INTEGER DEFAULT 0,
  arquivado_em  TEXT,
  usuario_id    INTEGER,
  criado        TEXT,
  atualizado    TEXT
);

-- HISTÓRICO — linha do tempo de cada paciente e de cada prontuário. É o que
-- sobrevive quando o paciente sai e volta.
CREATE TABLE IF NOT EXISTS historico (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidade     TEXT NOT NULL,
  entidade_id  INTEGER NOT NULL,
  evento       TEXT NOT NULL,
  detalhe      TEXT,
  usuario_id   INTEGER,
  usuario_nome TEXT,
  criado       TEXT
);

-- ANAMNESES. "tipo" diz qual formulário (psicanalise | ozonio | integrativas)
-- e "dados" guarda as respostas em JSON — acrescentar pergunta no modelo NÃO
-- exige mexer no banco.
-- É a anamnese que ABRE o prontuário: enquanto está em Rascunho não cria nada;
-- ao ser FINALIZADA, abre (ou reaproveita) a pasta do par paciente+procedimento.
CREATE TABLE IF NOT EXISTS anamneses (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id   INTEGER NOT NULL,
  tipo          TEXT NOT NULL,
  dados         TEXT,
  procedimento  TEXT,
  status        TEXT DEFAULT 'Rascunho',
  finalizada_em TEXT,
  prontuario_id INTEGER,
  profissional  TEXT,
  data          TEXT,
  usuario_id    INTEGER,
  criado        TEXT,
  atualizado    TEXT
);

-- Documentos por paciente
CREATE TABLE IF NOT EXISTS documentos_gestao (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER,
  tipo        TEXT,
  titulo      TEXT,
  arquivo     TEXT,
  data        TEXT,
  criado      TEXT
);

-- ------------------------------- índices ----------------------------------
CREATE INDEX IF NOT EXISTS idx_atend_data  ON atendimentos(data);
CREATE INDEX IF NOT EXISTS idx_atend_pac   ON atendimentos(paciente_id);
CREATE INDEX IF NOT EXISTS idx_pront_pac   ON prontuario(paciente_id);
CREATE INDEX IF NOT EXISTS idx_anam_pac    ON anamneses(paciente_id);
CREATE INDEX IF NOT EXISTS idx_preg_pront  ON prontuario_registros(prontuario_id);
CREATE INDEX IF NOT EXISTS idx_hist_ent    ON historico(entidade, entidade_id);

-- --------------------- as três regras gravadas no banco --------------------
-- Última linha de defesa: nem um backup restaurado por cima duplica número.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pront_numero
  ON prontuario(numero) WHERE numero IS NOT NULL;

-- A REGRA da clínica: um prontuário por paciente + procedimento. Mesmo que a
-- tela falhe, o banco recusa o segundo.
-- (a coluna se chama `especialidade` por herança; o que ela guarda é o NOME do
--  procedimento — ver o comentário da tabela procedimentos)
CREATE UNIQUE INDEX IF NOT EXISTS idx_pront_pac_esp
  ON prontuario(paciente_id, especialidade);

-- O código do paciente também não pode repetir.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pac_codigo
  ON pacientes(codigo) WHERE codigo IS NOT NULL AND codigo <> '';
