-- ==========================================================================
--  005 — TESTES DE RASTREIO: o catálogo e o que foi enviado ao paciente
--
--  Aplicada uma vez pelo `migrarEsquema()` e registrada em schema_migrations.
--
--  ==========================================================================
--  O DESENHO, EM UMA FRASE
--
--    modelo (código) → teste (catálogo) → envio (link do paciente)
--
--  As PERGUNTAS não estão aqui. Elas vivem em `testes-modelos.js`, do mesmo
--  jeito que as perguntas de anamnese vivem em MODELOS_ANAMNESE: pergunta é
--  ESTRUTURA, não dado. Guardá-las em tabela obrigaria uma migração para
--  corrigir uma vírgula num enunciado, e faria dois lugares responderem
--  "quais são as perguntas do RTA-20" — que é como eles passam a discordar.
--
--  O que É tabela: quais testes a clínica usa (podem ser desligados sem mexer
--  no código) e o que foi enviado a quem.
-- ==========================================================================

-- --------------------------------------------------------------------------
--  CATÁLOGO
--
--  `chave` casa com a chave do modelo no arquivo JS. É por ela que o envio
--  encontra as perguntas — e é UNIQUE porque duas linhas com a mesma chave
--  fariam a tela mostrar o mesmo teste duas vezes, com situações diferentes.
--
--  `nome` e `instrucoes` são CÓPIA do modelo, e editáveis: a clínica pode
--  querer chamar o RTAE-15 de "Autoestima (adolescentes)" ou reescrever a
--  instrução sem me chamar. O que nunca muda por aqui são as perguntas.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS testes (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave       TEXT NOT NULL UNIQUE,
  sigla       TEXT NOT NULL DEFAULT '',
  nome        TEXT NOT NULL,
  instrucoes  TEXT NOT NULL DEFAULT '',
  ativo       INTEGER NOT NULL DEFAULT 1,
  sort        INTEGER NOT NULL DEFAULT 0,
  criado      TEXT,
  atualizado  TEXT
);

-- --------------------------------------------------------------------------
--  ENVIOS — um por link gerado
--
--  `codigo` é o que vai na URL (/answer/<codigo>) e por isso é a coluna mais
--  exposta do banco inteiro: é a ÚNICA barreira entre a internet e as
--  respostas de um paciente identificado. Três defesas, e nenhuma sozinha
--  basta:
--
--    1. o código é SORTEADO de 62 símbolos, 8 a 11 caracteres — nunca
--       sequencial. Um código sequencial permitiria andar de vizinho em
--       vizinho lendo a clínica inteira;
--    2. UNIQUE, para dois pacientes jamais compartilharem link;
--    3. o link para de abrir quando o teste é respondido (regra na aplicação).
--
--  `respostas` é CIFRADO pela aplicação, como `anamneses.dados`: é sintoma de
--  ansiedade, depressão e ideação de uma pessoa com nome e CPF no mesmo banco.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teste_envios (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        TEXT NOT NULL UNIQUE,
  paciente_id   INTEGER NOT NULL,
  teste_chave   TEXT NOT NULL,
  prontuario_id INTEGER,

  -- SITUAÇÃO GUARDADA: criado → enviado → aberto → concluido.
  --
  -- "VENCIDO" NÃO ESTÁ AQUI, de propósito. Vencer é o relógio andando, não
  -- alguém clicando: se fosse coluna, dependeria de uma tarefa que passasse
  -- marcando linha — e no dia em que ela não rodasse, um teste vencido
  -- continuaria abrindo. É CALCULADO de `expira_em`, e por isso não tem como
  -- mentir. Mesma razão pela qual "concluído" É guardado: aquilo aconteceu.
  status        TEXT NOT NULL DEFAULT 'criado',

  -- Nulo = não expira (o pedido tem a caixa "não expirar", que desliga a data).
  expira_em     TEXT,

  msg_boas_vindas   TEXT,
  msg_agradecimento TEXT,

  respostas     TEXT,   -- JSON cifrado: { "chave_do_item": valor }
  avaliacao     TEXT,   -- JSON cifrado: os blocos que são do TERAPEUTA

  criado        TEXT,
  enviado_em    TEXT,
  aberto_em     TEXT,
  concluido_em  TEXT,
  criado_por    INTEGER,

  CONSTRAINT ck_envio_status CHECK (status IN ('criado','enviado','aberto','concluido'))
);

-- A busca por código acontece a CADA acesso ao link, vinda da internet aberta.
-- É a consulta mais quente da tabela e a única que um desconhecido dispara.
CREATE INDEX IF NOT EXISTS idx_envio_codigo    ON teste_envios(codigo);
CREATE INDEX IF NOT EXISTS idx_envio_paciente  ON teste_envios(paciente_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_envio_pasta     ON teste_envios(prontuario_id)
  WHERE prontuario_id IS NOT NULL;

COMMENT ON COLUMN teste_envios.status IS
  'criado | enviado | aberto | concluido. "vencido" é CALCULADO de expira_em — nunca gravado.';
COMMENT ON COLUMN teste_envios.expira_em IS
  'Nulo = não expira. Data no formato AAAA-MM-DD.';
COMMENT ON COLUMN teste_envios.respostas IS
  'JSON CIFRADO pela aplicação. Dado de saúde: sintoma relatado por paciente identificado.';
